<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="wfrm_Mant_Empleados.aspx.cs" Inherits="UX.Pantallas.Formularios.wfrm_Mant_Empleados" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
 <title>Mantenimiento de Empleados</title>
    <link href="../../Estilos/main.css" rel="stylesheet" />
    <script src="../../Javascript/notificacion.js"></script>
    <script src="../../Javascript/notificacion_II.js"></script>
</head>
<body class="homepage is-preload">
	<form id="form1" runat="server">	
	<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">

						<!-- Logo -->
							<h1 id="logo"><a href="wfrm_Inicio.aspx">Caja Costarricense del Seguro Social</a></h1>
							

						<!-- Nav -->
							<nav id="nav">
								<ul>
									<li><a class="icon solid fa-home" href="wfrm_Inicio.aspx"><span>Inicio</span></a></li>
									<li>
										<a href="#" class="icon fa-chart-bar"><span>Esquema Administrativo</span></a>
										<ul>
											<li><a href="wfrm_Mantenimiento_CCSS.aspx">Mantenimiento entidad</a></li>
											<li><a href="wfrm_Mant_Centros.aspx">Mantenimiento Centros</a></li>
											<li><a href="wfrm_Mant_Departamentos.aspx">Mantenimiento Departamentos</a></li>
											<li><a href="wfrm_Mant_Farmacias.aspx">Mantenimiento Farmacias</a></li>
											<li><a href="wfrm_Mant_Incapacidades.aspx">Mantenimiento Incapacidades</a></li>
											<li><a href="wfrm_Mant_Inventarios.aspx">Mantenimiento Inventarios</a></li>
											<li><a href="wfrm_Mant_Juntas.aspx">Mantenimiento Juntas</a></li>
											<li><a href="wfrm_Mant_Pedidos.aspx">Mantenimiento Pedidos</a></li>
											<li>
												
												
											</li>
										
										</ul>
									</li>
									
									<li>
										<a href="#" class="icon fa-chart-bar"><span>Esquema Medico</span></a>
										<ul>
											<li><a href="wfrm_Mant_Asegurados.aspx">Mantenimiento Asegurados</a></li>
											<li><a href="wfrm_Mant_Contratas.aspx">Mantenimiento Contratas</a></li>
											<li><a href="wfrm_Mant_Empleados.aspx">Mantenimiento Empleados</a></li>
											<li><a href="wfrm_Mant_Especialidades.aspx">Mantenimiento Especialidades</a></li>
										</ul>
									</li>
						
								</ul>
							</nav>

					</div>
				</section>
		</div>

	<!-- A partir de aqui empieza la personalizacion de las paginas individuales -->

		<div class="General" >
			<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>

        <div class="Recuadro_busqueda">

			<asp:TextBox ID="txt_filtro" runat="server" OnTextChanged="txt_filtro_TextChanged"></asp:TextBox>
        </div>
        <div class="Botones">
			
			  <asp:UpdatePanel ID="miUpdatePanel" runat="server">
				<ContentTemplate>
		
            <asp:Button ID="btn_Buscar" runat="server" Text="Buscar Dato por CODIGO JUNTA" OnClick="btn_Buscar_Click" />
            
				 </ContentTemplate>
			  </asp:UpdatePanel>
			   
			
           



        </div>	
			<asp:UpdatePanel ID="UpdatePanel1" runat="server">
			<ContentTemplate>
		
		<asp:GridView ID="gv_Empleados" runat="server" AutoGenerateSelectButton="True" SelectionMode="FullRowSelect" AutoPostBack="true" 
			OnSelectedIndexChanged="gv_Empleados_SelectedIndexChanged" AutoGenerateDeleteButton="True" OnRowDeleting="gv_Empleados_RowDeleting"  OnRowDeleted="gv_Empleados_RowDeleted">
            <EditRowStyle BorderStyle="Dotted" />
            <SelectedRowStyle BackColor="#FFCC99" BorderStyle="None" />
        </asp:GridView>
			</ContentTemplate>
		</asp:UpdatePanel>
			  
	<div class="Nuevos_Registros">
        <div class="div_Ced">
<asp:TextBox ID="txt_Ced" runat="server" MaxLength="13"></asp:TextBox> &nbsp;&nbsp;&nbsp;<asp:Label ID="lbl_Ced" runat="server" Text="Digita nuevo Cedula"></asp:Label>
		 
		
        </div>
		 
		<asp:TextBox ID="txt_Nombre" runat="server" Height="16px" MaxLength="35" Width="192px"></asp:TextBox><asp:Label ID="lbl_Nombre" runat="server" Text="Digita nuevo Nombre"></asp:Label>
        <div>
<asp:TextBox ID="txt_Tel" runat="server" MaxLength="9" TextMode="Number"></asp:TextBox> <br />
            <asp:Label ID="lbl_Tel" runat="server" Text="Digita nuevo Telefono"></asp:Label>
        </div>
		
		<asp:TextBox ID="txt_Dir" runat="server" MaxLength="50"></asp:TextBox><asp:Label ID="lbl_Dir" runat="server" Text="Digita nuevo Direccion"></asp:Label>
		<br />
        <asp:DropDownList ID="ddl_COD_JUNTA" runat="server" Width="248px" OnSelectedIndexChanged="ddl_COD_JUNTA_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:Label ID="lbl_Codigo" runat="server" Text="Selecciona codigo Junta"></asp:Label>
        <br />
        
        <br />
		<asp:Button ID="btn_Guardar" runat="server" Text="Guardar NUEVO" OnClick="btn_Guardar_Click" />
        &nbsp;
        <asp:Button ID="btn_editar" runat="server" Text="Editar Seleccionado" OnClick="btn_editar_Click" Enabled="False" />
		&nbsp;
        <asp:Button ID="bnt_limpiar" runat="server" Text="Limpiar Campos" OnClick="bnt_limpiar_Click" />
        </div>
		
		<
		<!-- Scripts  JS, no afectan grfico-->
			<script src="../../Javascript/jquery.min.js"></script>
			<script src="../../Javascript/jquery.dropotron.min.js"></script>
			<script src="../../Javascript/browser.min.js"></script>
			<script src="../../Javascript/breakpoints.min.js"></script>
			<script src="../../Javascript/util.js"></script>
			<script src="../../Javascript/main.js"></script>

		<!-- Notificacion Emergente-->


		
				</div>
	

			</form>

</body>
</html>
